#TODO: Generate me on prod
# Показывать запросы в логах
SHOW_REQ_LOG=1
#сервер адм панели
#DASHBOARD_HOST="127.0.0.1" FIXME: У нас проблемы с парсингом строковых данных
DASHBOARD_PORT=8081
ENABLE_LOG_FILE=0
LOG_PATH="."
MAX_BUS_QUEUE_SIZE=100000
BUS_REQUEST_TIMEOUT=1
DASHBOARD_AUTOUPDATE_PERIOD=10
HEALTHCHECK_TIMEOUT=15
